# File: .github/workflows/VIP.yml
name: Liu
on: 
  schedule: 
  - cron: '22 2 */2 * *' #此处为同步运行时间
  workflow_dispatch: 
  watch: 
   types: started 
  repository_dispatch:
    types: Liu
jobs: 
 repo-sync: 
     env: 
       PAT: ${{ github.event.client_payload.PAT || secrets.PAT }} #此处PAT需要申请
     runs-on: ubuntu-latest 
     if: github.event.repository.owner.id == github.event.sender.id 
     steps: 
      - uses: actions/checkout@v2 
        with: 
          persist-credentials: false 
           
      - name: VIP
        uses: repo-sync/github-sync@v2 
        if: env.PAT 
        with: 
          source_repo: "https://github.com/bullfly666/percollect.git" # liu大
          source_branch: "main" 
          destination_branch: "liu" # 按照自己仓库分支名称修改
          github_token: ${{ github.event.client_payload.PAT || secrets.PAT }}
